---@meta
--- A `Trace` object is used to capture and inspect feedback messages generated by command execution.
--- When passed to `spell:execute`, any textual output from the command will be collected into the trace.
---@class Trace
---@field content string|nil @Read-Only The concatenated output messages if collected; `nil` if empty.
Trace = {}

--- Creates and returns a new `Trace` instance for capturing command feedback.
---
--- ### Example
--- ```lua
--- local trace = Trace:new()
--- spell:execute("/data get entity @p", trace)
--- print("Command output:\n" .. trace.content)
--- ```
---
--- @return Trace trace A new, empty `Trace` object.
function Trace:new() end
